name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # -----------------------------
  # SAST – SonarQube Scan
  # -----------------------------
  sast:
    name: SAST (SonarQube)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=commando-x_vuln-bank
            -Dsonar.organization=commando-x
            -Dsonar.sources=.
            -Dsonar.python.version=3.9

      - name: Store SonarQube Results
        run: |
          mkdir -p security-results/sonarqube
          curl -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
               "${{ secrets.SONAR_HOST_URL }}/api/issues/search?projectKeys=vulnerable-bank" \
               > security-results/sonarqube/issues.json

      - name: Upload SonarQube Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-results
          path: security-results/sonarqube/
          retention-days: 90

  # -----------------------------
  # SCA – Dependency Scanning with Snyk
  # -----------------------------
  sca:
    name: Dependency Scanning (Snyk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=security-results/snyk/scan-results.json

      - name: Upload Snyk Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: security-results/snyk/scan-results.json
          retention-days: 90

  # -----------------------------
  # Container Scanning – Trivy
  # -----------------------------
  container_scan:
    name: Container Scanning (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fix Permissions on Workspace
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Build Docker Image
        run: docker build -t vulnerable-bank:latest .

      - name: Create Trivy Results Directory
        run: mkdir -p security-results/trivy

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-bank:latest'
          format: 'json'
          output: 'security-results/trivy/scan-results.json'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: 0  # Continue even if vulnerabilities are found

      - name: Upload Trivy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: security-results/trivy/scan-results.json
          retention-days: 90

  # -----------------------------
  # IaC Scanning – Checkov
  # -----------------------------
  iac_scan:
    name: IaC Scanning (Checkov)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Checkov Results Directory
        run: mkdir -p security-results/checkov

      - name: Run Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile,github_actions
          output_format: json
          output_file: security-results/checkov/results.json
          soft_fail: true  # Report issues without failing the job

      - name: Upload Checkov Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: security-results/checkov/results.json
          retention-days: 90

  # -----------------------------
  # Dynamic Analysis – OWASP ZAP
  # -----------------------------
  zap_scan:
    name: Dynamic Analysis (OWASP ZAP)
    runs-on: ubuntu-latest
    continue-on-error: true  # Allows the workflow to continue even if ZAP fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZAP Results Directory
        run: mkdir -p security-results/zap

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Use the alternative image from Docker Hub (or switch to GHCR if desired)
          docker_name: 'zaproxy/zap-stable:latest'
          target: 'http://localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-J security-results/zap/zap-results.json'

      - name: Upload ZAP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: security-results/zap/zap-results.json
          retention-days: 90

  # -----------------------------
  # Report – Generate HTML Summary Report
  # -----------------------------
  report:
    name: Generate HTML Report
    runs-on: ubuntu-latest
    needs: [sast, sca, container_scan, iac_scan, zap_scan]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Security Report
        run: |
          mkdir -p security-results
          echo "<!DOCTYPE html>
          <html>
          <head>
            <title>Security Scan Results</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              .tool-section { margin-bottom: 30px; }
              .severity-high { color: red; }
              .severity-medium { color: orange; }
              .severity-low { color: yellow; }
            </style>
          </head>
          <body>
            <h1>Security Scan Results</h1>
            <div class='tool-section'>
              <h2>Summary</h2>
              <p>Scan completed at $(date)</p>
              <p>Repository: $GITHUB_REPOSITORY</p>
              <p>Branch: $GITHUB_REF</p>
            </div>
          </body>
          </html>" > security-results/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-results/report.html
          retention-days: 90

  # -----------------------------
  # Deploy – Deployment Stage
  # -----------------------------
  deploy:
    name: Deploy to EC2
    needs: [sast, sca, container_scan, iac_scan, zap_scan, report]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          chmod +x deploy/deploy.sh
          ./deploy/deploy.sh
